---
#Deploying application on k8's cluster and cross checking whether the
#application is deployed successfully.
- name: Deploying {{ application_name }}
  shell: kubectl apply -f {{ application_deployment }} -n {{ app_ns }}

- include_tasks: /utils/k8s/status_app_pod.yml
  when: check_app_pod == 'yes'

- include_tasks: /utils/scm/openebs/check_replica_count.yml
  when: deploy_type == 'statefulset'

