---
# This util can deploy application in K8s cluster.
# The parameters required are
#     - app_yml ( Application spec)
#     - app_ns  ( namespace where application needs to be deployed)

- name: Deploy Application
  shell: kubectl apply -f {{ item }} -n {{ app_ns }}
  args:
    executable: /bin/bash
  with_items: "{{ app_yml }}"


